import express from "express";

const app = express();
app.use(express.text({ type: "*/*", limit: "2mb" }));

function scoreMatches(input, patterns) {
  let score = 0;
  for (const p of patterns) {
    if (p.test(input)) score++;
  }
  return score;
}

function respond(res, obfuscator, confidence, extra = undefined) {
  const body = { Obfuscator: obfuscator, Confidence: confidence };
  if (extra) body.Extra = extra;
  return res.json(body);
}

function hasAll(input, patterns) {
  return patterns.every((p) => p.test(input));
}

function hasAny(input, patterns) {
  return patterns.some((p) => p.test(input));
}

const detectors = [
  { name: "Luraph", exact: [/https:\/\/lura\.ph\//i, /luraph/i], patterns: [/bit32\.bxor/i, /string\.gsub/i, /\brepeat\s+if\b/i, /\bloadstring\b/i, /\bsetfenv\b/i] },
  { name: "UPX", exact: [/--\[\[\s*Ts file was generated by UPX/i, /\bUPX\b/i], patterns: [/Ts file was generated by UPX/i] },
  { name: "IronBrew", exact: [/--\s*this file was generated using ironbrew1/i, /ironbrew/i, /setfenv/i], patterns: [/\bgetfenv\b/i, /\bsetfenv\b/i, /\bloadstring\b/i, /string\.char/i, /string\.byte/i] },
  { name: "Threaded", exact: [/--\s*this file was obfuscated with the unveilr obf/i, /unveilr obf/i], patterns: [/return\s*\(\s*function\s*\([^)]*\)\s*return\s*\(\s*function/i, /\bwhile\s+\w+\s+do\b/i, /\bif\s+\w+\s*<\s*\(/i, /\(\d+\+1\)-1/, /\w+\[\(\d+\+1\)-1\]/, /\blocal\s+[A-Za-z0-9_,]{30,}/] },
  { name: "MoonVeil", exact: [/MoonVeil Obfuscator/i, /MoonVeil/i], patterns: [/\bEe\(/, /\bWc\[Ee\(/, /\bbit32\.bxor\b/i, /\bstring\.byte\b/i, /\bstring\.char\b/i] },
  { name: "Wearedevs", exact: [/--\[\[\s*v1\.0\.0\s*https:\/\/wearedevs\.net\/obfuscator\s*\]\]/i, /wearedevs\.net\/obfuscator/i], patterns: [/return\s*\(\s*function\(/i, /local\s+[A-Za-z]\s*=\s*\{/, /for\s+[A-Za-z],[A-Za-z]\s+in\s+ipairs/i] },
  { name: "Prometheus/25ms", exact: [/Prometheus/i, /25ms/i], patterns: [/return\s*\(\s*function\s*\(\s*\.\.\.\s*\)\s*local\s+[A-Za-z]\s*=\s*\{/i, /=\s*.+\s*;/, /string\.char/i, /base64/i] },
  { name: "Prometheus", exact: [/return\s*\(\s*function\s*\(\s*\.\.\.\s*\)\s*local\s+[A-Za-z]\s*=\s*\{/i], patterns: [/local\s+[A-Za-z]\s*=\s*\{/, /return\s*\(\s*function\(/i, /for\s+[A-Za-z],[A-Za-z]\s+in\s+ipairs/i] },
  { name: "IronBrew 2", exact: [/IronBrew 2/i, /IB2/i], patterns: [/\bgetfenv\b/i, /\bloadstring\b/i, /\bstring\.char\b/i, /\bstring\.byte\b/i, /\bbit32\./i] },
  { name: "IronBrew 1", exact: [/IronBrew 1/i, /IB1/i], patterns: [/\bgetfenv\b/i, /\bsetfenv\b/i, /\bloadstring\b/i] },
];

app.post("/api", (req, res) => {
  const input = String(req.body || "");
  if (!input.trim()) return respond(res, "Unknown", "0%");
  const normalized = input.replace(/\r\n/g, "\n");

  for (const d of detectors) {
    if (d.exact && hasAny(normalized, d.exact)) {
      if (d.name === "Prometheus/25ms") {
        const is25ms = /25ms|=\s*.+\s*;|base64/i.test(normalized);
        return respond(res, is25ms ? "Prometheus/25ms" : "Prometheus", "100%");
      }
      if (d.name === "Wearedevs") {
        const wadPatterns = [/return\s*\(\s*function\(/i, /local\s+[A-Za-z]\s*=\s*\{/, /for\s+[A-Za-z],[A-Za-z]\s+in\s+ipairs/i];
        const score = scoreMatches(normalized, wadPatterns);
        if (score >= 2) return respond(res, "Wearedevs", "100%");
        return respond(res, "Unknown", "50%", "Watermark found, but structure does not match Wearedevs closely.");
      }
      if (d.name === "IronBrew") {
        const score = scoreMatches(normalized, d.patterns);
        if (score >= 2) {
          const version = /setfenv/i.test(normalized) ? "IronBrew 1" : "IronBrew 2";
          return respond(res, version, "100%");
        }
        return respond(res, "IronBrew", "90%");
      }
      return respond(res, d.name, "100%");
    }
  }

  const structuredDetectors = [
    { name: "Threaded", patterns: [/return\s*\(\s*function\s*\([^)]*\)\s*return\s*\(\s*function/i, /\bwhile\s+\w+\s+do\b/i, /\bif\s+\w+\s*<\s*\(/i, /\(\d+\+1\)-1/, /\w+\[\(\d+\+1\)-1\]/, /\blocal\s+[A-Za-z0-9_,]{40,}/], threshold: 3 },
    { name: "MoonVeil", patterns: [/\bEe\(/, /\bWc\[Ee\(/, /\bbit32\.bxor\b/i, /\bstring\.byte\b/i, /\bstring\.char\b/i], threshold: 3 },
    { name: "Prometheus/25ms", patterns: [/return\s*\(\s*function\s*\(\s*\.\.\.\s*\)\s*local\s+[A-Za-z]\s*=\s*\{/i, /local\s+[A-Za-z]\s*=\s*\{/, /for\s+[A-Za-z],[A-Za-z]\s+in\s+ipairs/i, /string\.char/i, /base64/i, /=\s*.+\s*;/], threshold: 3 },
    { name: "Luraph", patterns: [/\bbit32\.bxor\b/i, /\bstring\.gsub\b/i, /\brepeat\s+if\b/i, /\bloadstring\b/i, /\bsetfenv\b/i], threshold: 3 },
    { name: "IronBrew", patterns: [/\bgetfenv\b/i, /\bsetfenv\b/i, /\bloadstring\b/i, /\bstring\.char\b/i, /\bstring\.byte\b/i], threshold: 3 },
  ];

  let best = { name: "Unknown", score: 0, threshold: 0 };
  for (const d of structuredDetectors) {
    const score = scoreMatches(normalized, d.patterns);
    if (score > best.score) best = { name: d.name, score, threshold: d.threshold };
  }

  if (best.score >= best.threshold) {
    const confidence = best.score === best.threshold ? "85%" : best.score >= best.threshold + 1 ? "95%" : "80%";
    return respond(res, best.name, confidence);
  }

  const fuzzyDetectors = [
    { name: "Threaded", patterns: [/while\s+\w+\s+do/i, /\(\d+\+1\)-1/, /\breturn\s*\(\s*function/i] },
    { name: "MoonVeil", patterns: [/\bbit32\.bxor\b/i, /\bstring\.char\b/i, /\bstring\.byte\b/i] },
    { name: "Prometheus", patterns: [/return\s*\(\s*function/i, /local\s+[A-Za-z]\s*=\s*\{/] },
    { name: "25ms", patterns: [/[A-Za-z0-9+/]{20,}={0,2}/, /\bstring\.char\b/i] },
    { name: "Luraph", patterns: [/\bstring\.gsub\b/i, /\brepeat\s+if\b/i, /\bbit32\.bxor\b/i] },
    { name: "IronBrew", patterns: [/\bgetfenv\b/i, /\bloadstring\b/i, /\bsetfenv\b/i] },
  ];

  let fuzzyBest = { name: "Unknown", score: 0 };
  for (const d of fuzzyDetectors) {
    const score = scoreMatches(normalized, d.patterns);
    if (score > fuzzyBest.score) fuzzyBest = { name: d.name, score };
  }

  if (fuzzyBest.score > 0) {
    const percent = Math.min(90, 40 + fuzzyBest.score * 15);
    return respond(res, fuzzyBest.name, `${percent}%`, "Heuristic match only. Add a watermark or sample output to improve accuracy.");
  }

  return respond(res, "Unknown", "0%");
});

app.listen(3000, () => console.log("Obf detector API running on port 3000"));
