const express = require("express")
const bodyParser = require("body-parser")

const app = express()
app.use(bodyParser.text({ type: "*/*" }))

function detectObf(script) {
  if (/https:\/\/lura\.ph\//.test(script)) return { Dumper: "Luraph", Confidence: "100%" }
  if (/--\[\[\s*obfuscated\s*@\s*discord\.gg\/25ms\s*\]\]/.test(script)) return { Dumper: "25ms", Confidence: "100%" }
  if (/--\[\[\s*v1\.0\.0\s*https:\/\/wearedevs\.net\/obfuscator\s*\]\]/.test(script)) return { Dumper: "Wearedevs", Confidence: "100%" }
  if (/--\s*\[\s*Ts file was generated by UPX \(VMProtect 1\.7 \[Max Protection\] F0RK\)\s*\]\s*--/.test(script)) return { Dumper: "UPX", Confidence: "100%" }
  if (/local\s+v0/.test(script)) return { Dumper: "Lua Obfuscator (v0)", Confidence: "100%" }
  if (/--\s*this file was generated using ironbrew1/i.test(script)) return { Dumper: "IronBrew1", Confidence: "100%" }
  if (/--\s*this file was obfuscated with the unveilr obf \(prom fork\)\s*at\s*https:\/\/discord\.gg\/threaded/i.test(script)) return { Dumper: "Threaded (UnveilR)", Confidence: "100%" }

  const alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
  for (let i = 0; i < alphabet.length; i++) {
    const v = alphabet[i]
    const regex = new RegExp(`return\\s*\\(\\s*function\\s*\\(\\s*\\.\\.\\.\\s*\\)\\s*local\\s+${v}`)
    if (regex.test(script)) return { Dumper: "Prometheus Fork", Confidence: "100%" }
  }

  return { Dumper: "Unknown", Confidence: "CONTACT mruptimee. TO ADD SUPPORT TO OBF" }
}

app.post("/api", (req, res) => {
  const script = req.body || ""
  const result = detectObf(script)
  res.json(result)
})

const PORT = process.env.PORT || 3000
app.listen(PORT, () => console.log(`Obfuscator API running on port ${PORT}`))
