import express from "express";
const app = express();
app.use(express.text({ type: "*/*" }));

app.post("/api", (req, res) => {
  const input = req.body;
  const json = (dumper, confidence) => res.json({ Dumper: dumper, Confidence: confidence });

  if (input.includes("https://lura.ph/")) return json("Luraph", "100%");
  if (/--\[\[\s*v1\.0\.0\s*https:\/\/wearedevs\.net\/obfuscator\s*\]\]/.test(input)) return json("Wearedevs", "100%");
  if (/--\[\[\s*Ts file was generated by UPX/i.test(input)) return json("UPX", "100%");
  if (/--\s*this file was generated using ironbrew1/i.test(input)) return json("IB1", "100%");
  if (/--\s*this file was obfuscated with the unveilr obf/i.test(input)) return json("Threaded", "100%");

  const alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
  for (let i = 0; i < alphabet.length; i++) {
    const v = alphabet[i];
    const regex = new RegExp(`return\\s*\\(\\s*function\\s*\\(\\s*\\.\\.\\.\\s*\\)\\s*local\\s+${v}`);
    if (regex.test(input)) return json("Prometheus", "100%");
  }

  const tableRegex = /(?:local|const)\s+\w+\s*=\s*\{([\s\S]*?)\}/i;
  const match = input.match(tableRegex);
  if (match) {
    const tableContent = match[1];
    const base64Regex = /[A-Za-z0-9+/]{4,}={0,2}/g;
    if (base64Regex.test(tableContent)) return json("25ms", "100%");
    const xorRegex = /\b\w+\[[^\]]+\]\s*=\s*\w+\([^\)]+\)\s*-\s*\w+\([^\)]+\)/;
    if (xorRegex.test(tableContent)) return json("25ms", "100%");
  }

  const LURAPH_PATTERNS = [
    /\blocal\s+\w+(?:,\w+){1,},\w+\s*=\s*pairs,bit32\.bxor,getmetatable,type\b/,
    /\b[A-Za-z0-9_]+,?[A-Za-z0-9_]*,?[A-Za-z0-9_]*=function\b/,
    /\brepeat\s+if\s+[A-Za-z0-9_]+>/,
    /\bbit32\s*\.\s*bxor\b/,
    /\bstring\.char\b.*\bstring\.byte\b/,
    /\bstring\.gsub\s*\(.*'[^A-Za-z0-9+/=]'/,
  ];
  for (const pattern of LURAPH_PATTERNS) if (pattern.test(input)) return json("Luraph", "100%");

  return json("Unknown", "CONTACT mruptimee TO ADD SUPPORT TO OBF");
});

app.listen(3000, () => console.log("Obf detector API running on port 3000"));
